const tintColorLight = "#2f95dc";
const tintColorDark = "#fff";

export default {
  light: {
    text: "#000",
    background: "#fff",
    tint: tintColorLight,
    tabIconDefault: "#ccc",
    tabIconSelected: tintColorLight,
  },
  dark: {
    text: "#fff",
    background: "#000",
    tint: tintColorDark,
    tabIconDefault: "#ccc",
    tabIconSelected: tintColorDark,
  },
};

export type ThemeColor =
  | "slate"
  | "gray"
  | "zinc"
  | "neutral"
  | "stone"
  | "red"
  | "orange"
  | "amber"
  | "yellow"
  | "lime"
  | "green"
  | "emerald"
  | "teal"
  | "cyan"
  | "sky"
  | "blue"
  | "indigo"
  | "violet"
  | "purple"
  | "fuchsia"
  | "pink"
  | "rose";

export interface ThemeColors {
  primary: string;
  secondary: string;
  accent: string;
  background: string;
  surface: string;
  surfaceLight: string;
  text: string;
  textMuted: string;
  textPrimary: string;
  textPrimaryMuted: string;
  destructive: string;
  destructivePressed: string;
}

export const themeColorMap: Record<ThemeColor, ThemeColors> = {
  // All colors should follow this exact pattern
  slate: {
    primary: "bg-slate-500 dark:bg-slate-400",
    secondary: "bg-slate-600 dark:bg-slate-500",
    accent: "bg-slate-400 dark:bg-slate-300",
    background: "bg-gray-50 dark:bg-gray-950",
    surface: "bg-white dark:bg-gray-900",
    surfaceLight: "bg-gray-100 dark:bg-gray-800",
    text: "text-gray-900 dark:text-gray-50",
    textMuted: "text-gray-600 dark:text-gray-400",
    textPrimary: "text-slate-50 dark:text-slate-50",
    textPrimaryMuted: "text-slate-200 dark:text-slate-200",
    destructive: "bg-red-500 dark:bg-red-600",
    destructivePressed: "active:bg-red-600 dark:active:bg-red-700",
  },
  gray: {
    primary: "bg-gray-500 dark:bg-gray-400",
    secondary: "bg-gray-600 dark:bg-gray-500",
    accent: "bg-gray-400 dark:bg-gray-300",
    background: "bg-gray-50 dark:bg-gray-950",
    surface: "bg-white dark:bg-gray-900",
    surfaceLight: "bg-gray-100 dark:bg-gray-800",
    text: "text-gray-900 dark:text-gray-50",
    textMuted: "text-gray-600 dark:text-gray-400",
    textPrimary: "text-gray-50 dark:text-gray-50",
    textPrimaryMuted: "text-gray-200 dark:text-gray-200",
    destructive: "bg-red-500 dark:bg-red-600",
    destructivePressed: "active:bg-red-600 dark:active:bg-red-700",
  },
  zinc: {
    primary: "bg-zinc-500 dark:bg-zinc-400",
    secondary: "bg-zinc-600 dark:bg-zinc-500",
    accent: "bg-zinc-400 dark:bg-zinc-300",
    background: "bg-gray-50 dark:bg-gray-950",
    surface: "bg-white dark:bg-gray-900",
    surfaceLight: "bg-gray-100 dark:bg-gray-800",
    text: "text-gray-900 dark:text-gray-50",
    textMuted: "text-gray-600 dark:text-gray-400",
    textPrimary: "text-zinc-50 dark:text-zinc-50",
    textPrimaryMuted: "text-zinc-200 dark:text-zinc-200",
    destructive: "bg-red-500 dark:bg-red-600",
    destructivePressed: "active:bg-red-600 dark:active:bg-red-700",
  },
  neutral: {
    primary: "bg-neutral-500 dark:bg-neutral-400",
    secondary: "bg-neutral-600 dark:bg-neutral-500",
    accent: "bg-neutral-400 dark:bg-neutral-300",
    background: "bg-gray-50 dark:bg-gray-950",
    surface: "bg-white dark:bg-gray-900",
    surfaceLight: "bg-gray-100 dark:bg-gray-800",
    text: "text-gray-900 dark:text-gray-50",
    textMuted: "text-gray-600 dark:text-gray-400",
    textPrimary: "text-gray-50 dark:text-gray-50",
    textPrimaryMuted: "text-gray-200 dark:text-gray-200",
    destructive: "bg-red-500 dark:bg-red-600",
    destructivePressed: "active:bg-red-600 dark:active:bg-red-700",
  },
  stone: {
    primary: "bg-stone-500 dark:bg-stone-400",
    secondary: "bg-stone-600 dark:bg-stone-500",
    accent: "bg-stone-400 dark:bg-stone-300",
    background: "bg-gray-50 dark:bg-gray-950",
    surface: "bg-white dark:bg-gray-900",
    surfaceLight: "bg-gray-100 dark:bg-gray-800",
    text: "text-gray-900 dark:text-gray-50",
    textMuted: "text-gray-600 dark:text-gray-400",
    textPrimary: "text-stone-50 dark:text-stone-50",
    textPrimaryMuted: "text-stone-200 dark:text-stone-200",
    destructive: "bg-red-500 dark:bg-red-600",
    destructivePressed: "active:bg-red-600 dark:active:bg-red-700",
  },
  red: {
    primary: "bg-red-500 dark:bg-red-400",
    secondary: "bg-red-600 dark:bg-red-500",
    accent: "bg-red-400 dark:bg-red-300",
    background: "bg-gray-50 dark:bg-gray-950",
    surface: "bg-white dark:bg-gray-900",
    surfaceLight: "bg-gray-100 dark:bg-gray-800",
    text: "text-gray-900 dark:text-gray-50",
    textMuted: "text-gray-600 dark:text-gray-400",
    textPrimary: "text-red-50 dark:text-red-50",
    textPrimaryMuted: "text-red-200 dark:text-red-200",
    destructive: "bg-red-600 dark:bg-red-700",
    destructivePressed: "active:bg-red-700 dark:active:bg-red-800",
  },
  orange: {
    primary: "bg-orange-500 dark:bg-orange-400",
    secondary: "bg-orange-600 dark:bg-orange-500",
    accent: "bg-orange-400 dark:bg-orange-300",
    background: "bg-gray-50 dark:bg-gray-950",
    surface: "bg-white dark:bg-gray-900",
    surfaceLight: "bg-gray-100 dark:bg-gray-800",
    text: "text-gray-900 dark:text-gray-50",
    textMuted: "text-gray-600 dark:text-gray-400",
    textPrimary: "text-orange-50 dark:text-orange-50",
    textPrimaryMuted: "text-orange-200 dark:text-orange-200",
    destructive: "bg-red-500 dark:bg-red-600",
    destructivePressed: "active:bg-red-600 dark:active:bg-red-700",
  },
  amber: {
    primary: "bg-amber-500 dark:bg-amber-400",
    secondary: "bg-amber-600 dark:bg-amber-500",
    accent: "bg-amber-400 dark:bg-amber-300",
    background: "bg-gray-50 dark:bg-gray-950",
    surface: "bg-white dark:bg-gray-900",
    surfaceLight: "bg-gray-100 dark:bg-gray-800",
    text: "text-gray-900 dark:text-gray-50",
    textMuted: "text-gray-600 dark:text-gray-400",
    textPrimary: "text-amber-950 dark:text-amber-950",
    textPrimaryMuted: "text-amber-900 dark:text-amber-900",
    destructive: "bg-red-500 dark:bg-red-600",
    destructivePressed: "active:bg-red-600 dark:active:bg-red-700",
  },
  yellow: {
    primary: "bg-yellow-500 dark:bg-yellow-400",
    secondary: "bg-yellow-600 dark:bg-yellow-500",
    accent: "bg-yellow-400 dark:bg-yellow-300",
    background: "bg-gray-50 dark:bg-gray-950",
    surface: "bg-white dark:bg-gray-900",
    surfaceLight: "bg-gray-100 dark:bg-gray-800",
    text: "text-gray-900 dark:text-gray-50",
    textMuted: "text-gray-600 dark:text-gray-400",
    textPrimary: "text-yellow-950 dark:text-yellow-950",
    textPrimaryMuted: "text-yellow-900 dark:text-yellow-900",
    destructive: "bg-red-500 dark:bg-red-600",
    destructivePressed: "active:bg-red-600 dark:active:bg-red-700",
  },
  lime: {
    primary: "bg-lime-500 dark:bg-lime-400",
    secondary: "bg-lime-600 dark:bg-lime-500",
    accent: "bg-lime-400 dark:bg-lime-300",
    background: "bg-gray-50 dark:bg-gray-950",
    surface: "bg-white dark:bg-gray-900",
    surfaceLight: "bg-gray-100 dark:bg-gray-800",
    text: "text-gray-900 dark:text-gray-50",
    textMuted: "text-gray-600 dark:text-gray-400",
    textPrimary: "text-lime-950 dark:text-lime-950",
    textPrimaryMuted: "text-lime-900 dark:text-lime-900",
    destructive: "bg-red-500 dark:bg-red-600",
    destructivePressed: "active:bg-red-600 dark:active:bg-red-700",
  },
  green: {
    primary: "bg-green-500 dark:bg-green-400",
    secondary: "bg-green-600 dark:bg-green-500",
    accent: "bg-green-400 dark:bg-green-300",
    background: "bg-gray-50 dark:bg-gray-950",
    surface: "bg-white dark:bg-gray-900",
    surfaceLight: "bg-gray-100 dark:bg-gray-800",
    text: "text-gray-900 dark:text-gray-50",
    textMuted: "text-gray-600 dark:text-gray-400",
    textPrimary: "text-green-50 dark:text-green-50",
    textPrimaryMuted: "text-green-200 dark:text-green-200",
    destructive: "bg-red-500 dark:bg-red-600",
    destructivePressed: "active:bg-red-600 dark:active:bg-red-700",
  },
  emerald: {
    primary: "bg-emerald-500 dark:bg-emerald-400",
    secondary: "bg-emerald-600 dark:bg-emerald-500",
    accent: "bg-emerald-400 dark:bg-emerald-300",
    background: "bg-gray-50 dark:bg-gray-950",
    surface: "bg-white dark:bg-gray-900",
    surfaceLight: "bg-gray-100 dark:bg-gray-800",
    text: "text-gray-900 dark:text-gray-50",
    textMuted: "text-gray-600 dark:text-gray-400",
    textPrimary: "text-emerald-50 dark:text-emerald-50",
    textPrimaryMuted: "text-emerald-200 dark:text-emerald-200",
    destructive: "bg-red-500 dark:bg-red-600",
    destructivePressed: "active:bg-red-600 dark:active:bg-red-700",
  },
  teal: {
    primary: "bg-teal-500 dark:bg-teal-400",
    secondary: "bg-teal-600 dark:bg-teal-500",
    accent: "bg-teal-400 dark:bg-teal-300",
    background: "bg-gray-50 dark:bg-gray-950",
    surface: "bg-white dark:bg-gray-900",
    surfaceLight: "bg-gray-100 dark:bg-gray-800",
    text: "text-gray-900 dark:text-gray-50",
    textMuted: "text-gray-600 dark:text-gray-400",
    textPrimary: "text-teal-50 dark:text-teal-50",
    textPrimaryMuted: "text-teal-200 dark:text-teal-200",
    destructive: "bg-red-500 dark:bg-red-600",
    destructivePressed: "active:bg-red-600 dark:active:bg-red-700",
  },
  cyan: {
    primary: "bg-cyan-500 dark:bg-cyan-400",
    secondary: "bg-cyan-600 dark:bg-cyan-500",
    accent: "bg-cyan-400 dark:bg-cyan-300",
    background: "bg-gray-50 dark:bg-gray-950",
    surface: "bg-white dark:bg-gray-900",
    surfaceLight: "bg-gray-100 dark:bg-gray-800",
    text: "text-gray-900 dark:text-gray-50",
    textMuted: "text-gray-600 dark:text-gray-400",
    textPrimary: "text-cyan-50 dark:text-cyan-50",
    textPrimaryMuted: "text-cyan-200 dark:text-cyan-200",
    destructive: "bg-red-500 dark:bg-red-600",
    destructivePressed: "active:bg-red-600 dark:active:bg-red-700",
  },
  sky: {
    primary: "bg-sky-500 dark:bg-sky-400",
    secondary: "bg-sky-600 dark:bg-sky-500",
    accent: "bg-sky-400 dark:bg-sky-300",
    background: "bg-gray-50 dark:bg-gray-950",
    surface: "bg-white dark:bg-gray-900",
    surfaceLight: "bg-gray-100 dark:bg-gray-800",
    text: "text-gray-900 dark:text-gray-50",
    textMuted: "text-gray-600 dark:text-gray-400",
    textPrimary: "text-sky-50 dark:text-sky-50",
    textPrimaryMuted: "text-sky-200 dark:text-sky-200",
    destructive: "bg-red-500 dark:bg-red-600",
    destructivePressed: "active:bg-red-600 dark:active:bg-red-700",
  },
  blue: {
    primary: "bg-blue-500 dark:bg-blue-400",
    secondary: "bg-blue-600 dark:bg-blue-500",
    accent: "bg-blue-400 dark:bg-blue-300",
    background: "bg-gray-50 dark:bg-gray-950",
    surface: "bg-white dark:bg-gray-900",
    surfaceLight: "bg-gray-100 dark:bg-gray-800",
    text: "text-gray-900 dark:text-gray-50",
    textMuted: "text-gray-600 dark:text-gray-400",
    textPrimary: "text-white dark:text-white",
    textPrimaryMuted: "text-blue-100 dark:text-blue-100",
    destructive: "bg-red-500 dark:bg-red-600",
    destructivePressed: "active:bg-red-600 dark:active:bg-red-700",
  },
  indigo: {
    primary: "bg-indigo-500 dark:bg-indigo-400",
    secondary: "bg-indigo-600 dark:bg-indigo-500",
    accent: "bg-indigo-400 dark:bg-indigo-300",
    background: "bg-gray-50 dark:bg-gray-950",
    surface: "bg-white dark:bg-gray-900",
    surfaceLight: "bg-gray-100 dark:bg-gray-800",
    text: "text-gray-900 dark:text-gray-50",
    textMuted: "text-gray-600 dark:text-gray-400",
    textPrimary: "text-indigo-50 dark:text-indigo-50",
    textPrimaryMuted: "text-indigo-200 dark:text-indigo-200",
    destructive: "bg-red-500 dark:bg-red-600",
    destructivePressed: "active:bg-red-600 dark:active:bg-red-700",
  },
  violet: {
    primary: "bg-violet-500 dark:bg-violet-400",
    secondary: "bg-violet-600 dark:bg-violet-500",
    accent: "bg-violet-400 dark:bg-violet-300",
    background: "bg-gray-50 dark:bg-gray-950",
    surface: "bg-white dark:bg-gray-900",
    surfaceLight: "bg-gray-100 dark:bg-gray-800",
    text: "text-gray-900 dark:text-gray-50",
    textMuted: "text-gray-600 dark:text-gray-400",
    textPrimary: "text-violet-50 dark:text-violet-50",
    textPrimaryMuted: "text-violet-200 dark:text-violet-200",
    destructive: "bg-red-500 dark:bg-red-600",
    destructivePressed: "active:bg-red-600 dark:active:bg-red-700",
  },
  purple: {
    primary: "bg-purple-500 dark:bg-purple-400",
    secondary: "bg-purple-600 dark:bg-purple-500",
    accent: "bg-purple-400 dark:bg-purple-300",
    background: "bg-gray-50 dark:bg-gray-950",
    surface: "bg-white dark:bg-gray-900",
    surfaceLight: "bg-gray-100 dark:bg-gray-800",
    text: "text-gray-900 dark:text-gray-50",
    textMuted: "text-gray-600 dark:text-gray-400",
    textPrimary: "text-white dark:text-white",
    textPrimaryMuted: "text-purple-100 dark:text-purple-100",
    destructive: "bg-red-500 dark:bg-red-600",
    destructivePressed: "active:bg-red-600 dark:active:bg-red-700",
  },
  fuchsia: {
    primary: "bg-fuchsia-500 dark:bg-fuchsia-400",
    secondary: "bg-fuchsia-600 dark:bg-fuchsia-500",
    accent: "bg-fuchsia-400 dark:bg-fuchsia-300",
    background: "bg-gray-50 dark:bg-gray-950",
    surface: "bg-white dark:bg-gray-900",
    surfaceLight: "bg-gray-100 dark:bg-gray-800",
    text: "text-gray-900 dark:text-gray-50",
    textMuted: "text-gray-600 dark:text-gray-400",
    textPrimary: "text-fuchsia-50 dark:text-fuchsia-50",
    textPrimaryMuted: "text-fuchsia-200 dark:text-fuchsia-200",
    destructive: "bg-red-500 dark:bg-red-600",
    destructivePressed: "active:bg-red-600 dark:active:bg-red-700",
  },
  pink: {
    primary: "bg-pink-500 dark:bg-pink-400",
    secondary: "bg-pink-600 dark:bg-pink-500",
    accent: "bg-pink-400 dark:bg-pink-300",
    background: "bg-gray-50 dark:bg-gray-950",
    surface: "bg-white dark:bg-gray-900",
    surfaceLight: "bg-gray-100 dark:bg-gray-800",
    text: "text-gray-900 dark:text-gray-50",
    textMuted: "text-gray-600 dark:text-gray-400",
    textPrimary: "text-pink-50 dark:text-pink-50",
    textPrimaryMuted: "text-pink-200 dark:text-pink-200",
    destructive: "bg-red-500 dark:bg-red-600",
    destructivePressed: "active:bg-red-600 dark:active:bg-red-700",
  },
  rose: {
    primary: "bg-rose-500 dark:bg-rose-400",
    secondary: "bg-rose-600 dark:bg-rose-500",
    accent: "bg-rose-400 dark:bg-rose-300",
    background: "bg-gray-50 dark:bg-gray-950",
    surface: "bg-white dark:bg-gray-900",
    surfaceLight: "bg-gray-100 dark:bg-gray-800",
    text: "text-gray-900 dark:text-gray-50",
    textMuted: "text-gray-600 dark:text-gray-400",
    textPrimary: "text-rose-50 dark:text-rose-50",
    textPrimaryMuted: "text-rose-200 dark:text-rose-200",
    destructive: "bg-red-500 dark:bg-red-600",
    destructivePressed: "active:bg-red-600 dark:active:bg-red-700",
  },
};
